### ISSUE TITLE
`ERR_TOO_MANY_REDIRECTS` on subdomain for website hosted on vercel

### ISSUE THREAD

**Issue by zvikasdongre** [is-amazing/register#174]
Hello there,
For some reason, the domain vikas.is-amaz.ing domain keeps redirecting back to itself, resulting in `ERR_TOO_MANY_REDIRECTS`.

The website is hosted on vercel, zvikasdongre.vercel.app (PR: #47)

**Comment by Joabutt** [comment]
remove the is-really.cool domain and create a new pr for the is-amazing domain, as old domains were not updated.

**Comment by zvikasdongre** [comment]
Sure, but one thing I wanted to ask, vercel requires the subdomain to have a `CNAME` record, so should I put the value of the `CNAME` record in `url` field in the json file?

**Comment by Joabutt** [comment]
yep
